name: kind-ci
on:
  # enable running this on merges + presubmits when the action has tests that it will execute
  # push:
  #   branches: [main]
  # pull_request:
  workflow_dispatch:
jobs:
  test-kind:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8sVersion: ["1.23.x", "1.24.x", "1.25.x", "1.26.x", "1.27.x", "1.28.x", "1.29.x"]
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: ./.github/actions/install-deps
      with:
          k8sVersion: ${{ matrix.k8sVersion }}
    - name: Kind Cluster
      uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
    - name: check kind cluster and taint nodes
      shell: bash
      run: |
        kubectl config current-context
        kubectl get nodes
        kubectl taint nodes chart-testing-control-plane CriticalAddonsOnly:NoSchedule
    - name: Enable the actionlint matcher
      shell: bash
      run: echo "::add-matcher::.github/actionlint-matcher.json"
    - name: install pyroscope
      shell: bash
      run: | 
        curl -fL https://github.com/grafana/pyroscope/releases/download/v1.1.5/profilecli_1.1.5_linux_amd64.tar.gz | tar xz profilecli
        chmod +x profilecli
        sudo mv profilecli /usr/local/bin
    - name: install prometheus 
      uses: ./.github/actions/install-prometheus
    - name: install grafana 
      uses: ./.github/actions/install-grafana
    - name: install kwok and controller
      shell: bash
      run: |
        make toolchain
        make install-kwok
        KWOK_REPO=kind.local KIND_CLUSTER_NAME=chart-testing make apply-with-kind
    - name: apply nodepool 
      shell: bash
      run: |
        # Setup node pool
        cat <<EOF | envsubst | kubectl apply -f -
        apiVersion: karpenter.sh/v1beta1
        kind: NodePool
        metadata:
          name: default
        spec:
          template:
            spec:
              requirements:
                - key: kubernetes.io/arch
                  operator: In
                  values: ["amd64"]
                - key: kubernetes.io/os
                  operator: In
                  values: ["linux"]
                - key: karpenter.sh/capacity-type
                  operator: In
                  values: ["spot"]
              nodeClassRef:
                name: nil
          limits:
            cpu: 1500
          disruption:
            consolidationPolicy: WhenUnderutilized
            expireAfter: 720h # 30 * 24h = 720h
        EOF
    - name: ping cluster
      shell: bash
      run: | 
        kubectl get pods -n kube-system | grep karpenter 
        kubectl get nodepools
        kubectl get pods -A
        kubectl describe nodes
    - name: run performance simulation
      shell: bash
      run: | 
        FOCUS="Perf" make e2etests
    - name: cleanup 
      shell: bash
      run: | 
        kubectl delete nodepools --all 
        make delete
        make uninstall-kwok
        